### PR TITLE
fix: Use simple prompts for register commands on Windows

### LINKED ISSUE #924: infracost register outputs lines twice on Windows
I noticed the name/email output was doubled:
```
C:\infracost>infracost.exe register
Please enter your name and email address to get an API key.
See our FAQ (https://www.infracost.io/docs/faq) for more details.
Name: Txxxxr
Name: Txxxxr
Email: xxxx@gmail.com
Email: xxxx@gmail.com

Thank you Txxxxxr!
Your API key is: xxxx
```

### PR DESCRIPTION
**Pull request by vdmgolub**
The prompt libraries like promptui or survey produce double output on Windows.
Using simple prompts solves the issue, but doesn't alter experience for
Linux/macOS users.

Fixes #924 and #1265.

### CODE REVIEW

File: internal/ui/promts.go [hunk 1]
```diff
@@ -0,0 +1,57 @@
...
+		if input != "" {
+			break
+		}
+	}
+
+	return input
+}
+
+func YesNoPrompt(label string) bool {
+	choices := "y/N"
```
Comment (hugorut) [inline internal/ui/promts.go:37]:
```suggestion
	choices := "y/n"
```

File: internal/ui/promts.go [hunk 2]
```diff
@@ -0,0 +1,57 @@
...
+	input := ""
```
Comment (hugorut) [inline internal/ui/promts.go:38]:
```suggestion

```

File: internal/ui/promts.go [hunk 3]
```diff
@@ -0,0 +1,57 @@
...
+	reader := bufio.NewReader(os.Stdin)
+
+	for {
+		fmt.Fprintf(os.Stdout, "%s [%s] ", label, choices)
+		input, _ = reader.ReadString('\n')
```
Comment (hugorut) [inline internal/ui/promts.go:43]:
```suggestion
		input, _ := reader.ReadString('\n')
```

File: internal/ui/promts.go [hunk 4]
```diff
@@ -0,0 +1,57 @@
+package ui
+
+import (
+	"bufio"
+	"fmt"
+	"os"
+	"strings"
+)
+
+type ValidateFn func(input string) error
```
Comment (hugorut) [inline internal/ui/promts.go:10]: docs on exported types please - also `StringPrompt` and `YesNoPrompt`

File: cmd/infracost/register.go [hunk 5]
```diff
@@ -143,88 +144,73 @@ func registerCmd(ctx *config.RunContext) *cobra.Command {
...
-	}
-	name, err := p.Run()
-	name = strings.TrimSpace(name)
+	name, err := stringPrompt("Name", func(input string) error {
+		input = strings.TrimSpace(input)
+		if input == "" {
+			return errors.New("Please enter a name")
+		}
+		return nil
+	})
```
Comment (hugorut) [inline cmd/infracost/register.go:153]: Can we extract these funcs to the ui pkg so they're inline with the interface

**Review by hugorut — COMMENTED** [review]
few tweaks

File: cmd/infracost/register.go (hunk 5 above)
Comment (hugorut) [reply cmd/infracost/register.go:153]: by that i mean the validate func

Comment (hugorut) [reply cmd/infracost/register.go:153]: so:

```
func(input string) error {
		input = strings.TrimSpace(input)
		if input == "" {
			return errors.New("Please enter a name")
		}
		return nil
	}
```

File: internal/ui/promts.go (hunk 1 above)
Comment (vdmgolub) [reply internal/ui/promts.go:37]: `N` means it's the default behavior if left empty. Same as promptui shows it.

File: cmd/infracost/register.go (hunk 5 above)
Comment (vdmgolub) [reply cmd/infracost/register.go:153]: I'm not sure I follow. `ui` provides prompts to be used anywhere, but these validate functions are unique for `register` command. I would see such function having "Please enter a <any field name>" that takes an argument with the error message, and it seems redundant. It may also make sense to introduce `required` flag for the `StringPrompt`.

File: internal/ui/promts.go (hunk 2 above)
Comment (vdmgolub) [reply internal/ui/promts.go]: Updated.

File: internal/ui/promts.go (hunk 4 above)
Comment (vdmgolub) [reply internal/ui/promts.go:13]: Updated.

File: cmd/infracost/register.go (hunk 5 above)
Comment (hugorut) [reply cmd/infracost/register.go:153]: my preference would be to have this as exported funcs in the ui pkg like so:

```
var (
   ValidateName ValidateFn = func(input string) error {
		input = strings.TrimSpace(input)
		if input == "" {
			return errors.New("Please enter a name")
		}
		return nil
    }
    ValidateEmail ValidateFn = func(input string) error {
		if input == "" {
			return errors.New("Please enter an email")
		}
		match, err := regexp.MatchString(".+@.+", input)
		if err != nil {
			return errors.New("Unable to validate email")
		}
		if !match {
			return errors.New("Please enter a valid email")
		}
		return nil
	}
)

type ValidateFn func(input string) error

```

this seems quite generic to me

Comment (hugorut) [reply cmd/infracost/register.go:153]: but if you feel more comfortable with it stuffed in register the thats ok with me

Comment (vdmgolub) [reply cmd/infracost/register.go:153]: I see, but we still need to provide a `label` for the prompts. So having for example `StringPrompt("Foobar", ui.ValidateName)` will show `Please enter a name` instead of `Please enter a foobar`. With the email validation it may make more sense introducing `EmailPrompt` function so there is no disconnect between the label and error messages.

Comment (hugorut) [reply cmd/infracost/register.go:153]: yeah but reading `StringPrompt("Foobar", ui.ValidateName)` you'd realise validateName isn't the valid validate function. So you'd just create another function. If you really want to make it generic - which I don't feel theres too much benefit in this case then you can just have a function that decorates the validate function. e.g:


```go

func ValidateStringNotEmpty(emptyMsg string) ValidateFn {
    return func(input string) error {
		input = strings.TrimSpace(input)
		if input == "" {
			return errors.New(emptyMsg)
		}
		return nil
    }
}
```

this would be used as:

```go
ui.StringPrompt("Foobar", ui.ValidateStringNotEmpty("foobar cannot be empty")
```

Comment (hugorut) [reply cmd/infracost/register.go:153]: let's just stick with the original functionality tho

**Review by hugorut — APPROVED** [review]
✅

File: cmd/infracost/register.go (hunk 5 above)
Comment (vdmgolub) [reply cmd/infracost/register.go:153]: Yeah, I guess we can iterate on that when we need these simple prompts in other places 👍
