### PR TITLE
fix(aws): fix DX Gateway Associate region when using Terraform state

### LINKED ISSUE #349: Cost calculation differ between remote state and plan based calculation
I am prototyping infracost and I have faced strange issue. For some unknown reasons cost calculation are different between those two calculations:
- `infracost --no-color --tfdir . --tfplan ${PLAN}`
- `infracost --no-color --tfdir . --use-tfstate`

Terraform plan is empty:

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:

Terraform will perform the following actions:

Plan: 0 to add, 0 to change, 0 to destroy.
```

Diff between calculations:
```
11c11 
<   ├ Transit gateway attachment                                                              730  hours        0.0500       0.0500       36.5000    
---
>   ├ Transit gateway attachment                                                              730  hours        0.0600       0.0600       43.8000    
13c13
<   Total                                                                                                                     0.0500       36.5000   
---
>   Total                                                                                                                     0.0600       43.8000   
45c45
<   OVERALL TOTAL (USD)                                                                                                       0.1940      141.6200  
---
>   OVERALL TOTAL (USD)                                                                                                       0.2040      148.9200   
```

### PR DESCRIPTION
**Pull request by aliscott**
Fixes #349.

### CODE REVIEW

File: internal/providers/terraform/aws/dx_gateway_association.go [hunk 1]
```diff
@@ -8,14 +8,21 @@ import (
 
 func GetDXGatewayAssociationRegistryItem() *schema.RegistryItem {
 	return &schema.RegistryItem{
-		Name:  "aws_dx_gateway_association",
-		RFunc: NewDXGatewayAssociation,
+		Name:                "aws_dx_gateway_association",
+		RFunc:               NewDXGatewayAssociation,
+		ReferenceAttributes: []string{"associated_gateway_id"},
```
Comment (alikhajeh1) [inline internal/providers/terraform/aws/dx_gateway_association.go:13]: Should we document this feature in the contributing docs? I suspect few of our contributors know about it

**Review by alikhajeh1 — APPROVED** [review]

File: internal/providers/terraform/aws/dx_gateway_association.go (hunk 1 above)
Comment (alikhajeh1) [reply internal/providers/terraform/aws/dx_gateway_association.go:13]: Yep, it's fine to say that launching a resource is needed, I suspect most infracost contributors will be used to launching with TF
