### PR TITLE
fix: halts panic when attribute has been redeclared as a child block

### LINKED ISSUE #1871: `interface conversion` panic in HCL provider
Version: v0.10.7

Stacktrace:
```
interface conversion: interface {} is json.RawMessage, not []interface {}
goroutine 69 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x68
main.(*parallelRunner).run.func1.1()
	github.com/infracost/infracost/cmd/infracost/run.go:304 +0x40
panic({0x1064980c0, 0x14000def650})
	runtime/panic.go:838 +0x204
github.com/infracost/infracost/internal/providers/terraform.marshalBlock(0x14000661bf0?, 0x5?)
	github.com/infracost/infracost/internal/providers/terraform/hcl_provider.go:545 +0x350
github.com/infracost/infracost/internal/providers/terraform.marshalBlock(0x140006619d8?, 0x8?)
	github.com/infracost/infracost/internal/providers/terraform/hcl_provider.go:541 +0x140
github.com/infracost/infracost/internal/providers/terraform.(*HCLProvider).getResourceOutput(_, _)
	github.com/infracost/infracost/internal/providers/terraform/hcl_provider.go:373 +0x3bc
github.com/infracost/infracost/internal/providers/terraform.(*HCLProvider).marshalModule(0x140009dc3c0, 0x1400075fa18)
	github.com/infracost/infracost/internal/providers/terraform/hcl_provider.go:312 +0x1f0
github.com/infracost/infracost/internal/providers/terraform.(*HCLProvider).modulesToPlanJSON(0x140009dc3c0, 0x12f1e9d38?)
	github.com/infracost/infracost/internal/providers/terraform/hcl_provider.go:283 +0x158
github.com/infracost/infracost/internal/providers/terraform.(*HCLProvider).LoadPlanJSONs(0x140009dc3c0)
	github.com/infracost/infracost/internal/providers/terraform/hcl_provider.go:206 +0x98
github.com/infracost/infracost/internal/providers/terraform.(*HCLProvider).LoadResources(0x140004a5080?, 0x4?)
	github.com/infracost/infracost/internal/providers/terraform/hcl_provider.go:155 +0x28
main.(*parallelRunner).runProjectConfig(0x140004e7770, 0x140003d1d80)
	github.com/infracost/infracost/cmd/infracost/run.go:474 +0xf40
main.(*parallelRunner).run.func1()
	github.com/infracost/infracost/cmd/infracost/run.go:310 +0x190
golang.org/x/sync/errgroup.(*Group).Go.func1()
	golang.org/x/sync@v0.0.0-20220601150217-0de741cfad7f/errgroup/errgroup.go:75 +0x60
created by golang.org/x/sync/errgroup.(*Group).Go
	golang.org/x/sync@v0.0.0-20220601150217-0de741cfad7f/errgroup/errgroup.go:72 +0xa8
```

### PR DESCRIPTION
**Pull request by hugorut**
Fixes #1871

Resolves interface conversion panic when an block has an attribute which has been redeclared as a child block.
This is an invalid state and would be incorrect Terraform, hence why we haven't encountered this problem before.
We now handle this case by ignoring the child block definition and putting an entry into the debug log.

### CODE REVIEW

**Review by aliscott — APPROVED** [review]

File: internal/providers/terraform/hcl_provider.go [hunk 1]
```diff
@@ -539,10 +539,19 @@ func marshalBlock(block *hcl.Block, jsonValues map[string]interface{}) {
...
-			marshalBlock(b, childValues)
+			p.marshalBlock(b, childValues)
 		}
 
 		if v, ok := jsonValues[key]; ok {
+			if _, ok := v.(json.RawMessage); ok {
+				p.logger.WithFields(log.Fields{
+					"parent_block": block.LocalName(),
+					"child_block":  b.LocalName(),
+				}).Debugf("skipping attribute: %s that has also been declared as a child block", key)
```
Comment (aliscott) [inline internal/providers/terraform/hcl_provider.go:550]:
```suggestion
				}).Debugf("skipping attribute '%s' that has also been declared as a child block", key)
```
ignore if this is too picky.
