### PR TITLE
fix: solve range panic with terragrunt due to mismatch in project ctx

### LINKED ISSUE #1281: Terragrunt project count mismatch causes fatal panic
I'm currently evaluating infracost as part of our stack and unfortunately, I'm running into the below issue. 

For context, the project/directory I'm running the breakdown command against contains multiple modules/subfolders that each contain their own terragrunt.hcl. Some of which I'm filtering out using `export INFRACOST_TERRAGRUNT_FLAGS="--terragrunt-exclude-dir helm-* --terragrunt-exclude-dir k8s-*".

If I run the same command against an individual module/subfolder everything is working as expected.
`
```
`$ infracost breakdown --path .`

Detected Terragrunt directory at .
  ✔ Running terragrunt run-all terragrunt-info
  ✔ Running terragrunt run-all plan
  ✔ Running terragrunt show for each project
  ✔ Calculating monthly cost estimate


Error: An unexpected error occurred

runtime error: index out of range [1] with length 1
goroutine 1 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.17.5/x64/src/runtime/debug/stack.go:24 +0x65
main.handleUnexpectedErr(0x0, {0x11ceea0, 0xc000040fc0})
        /home/runner/work/infracost/infracost/cmd/infracost/main.go:170 +0x45
main.main.func1()
        /home/runner/work/infracost/infracost/cmd/infracost/main.go:42 +0x69
panic({0x11ceea0, 0xc000040fc0})
        /opt/hostedtoolcache/go/1.17.5/x64/src/runtime/panic.go:1038 +0x215
github.com/infracost/infracost/internal/apiclient.(*DashboardAPIClient).AddRun(0xc0004a7a68, 0xc0002b4a80, {0xc00041c1b8, 0x1, 0xc8}, {{0x1423a0b, 0x3}, {0x0, 0x0}, {0x0, ...}, ...})
        /home/runner/work/infracost/infracost/internal/apiclient/dashboard.go:91 +0xb0e
main.runMain(0xc0002f6500, 0xc0002b4a80)
        /home/runner/work/infracost/infracost/cmd/infracost/run.go:166 +0xb97
main.breakdownCmd.func1(0xc0002f6500, {0x1424d17, 0x2, 0x2})
        /home/runner/work/infracost/infracost/cmd/infracost/breakdown.go:42 +0x15c
github.com/spf13/cobra.(*Command).execute(0xc0002f6500, {0xc00029f760, 0x2, 0x2})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:852 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc0002af400)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x3ad
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
main.main()
        /home/runner/work/infracost/infracost/cmd/infracost/main.go:55 +0x116

Environment:
Infracost v0.9.16
```

### PR DESCRIPTION
**Pull request by hugorut**
fixes #1281

* Solves issue where enable dashboard with a terragrunt run caused fatal panic. This was due to the project ctx not mapping 1-1 with the output projects. This PR solves this by creating same length `projectContexts` as output `projects`.
* Adds goldenfile coverage for dashboard enabled

### CODE REVIEW

File: cmd/infracost/cmd_test.go [hunk 1]
```diff
@@ -32,9 +37,9 @@ func DefaultOptions() *GoldenFileOptions {
 	}
 }
 
-func GoldenFileCommandTest(t *testing.T, testName string, args []string, options *GoldenFileOptions) {
-	if options == nil {
-		options = DefaultOptions()
+func GoldenFileCommandTest(t *testing.T, testName string, args []string, testOptions *GoldenFileOptions, configOptions ...func(*config.Config)) {
```
Comment (aliscott) [inline cmd/infracost/cmd_test.go:40]: 🙌

**Review by aliscott — APPROVED** [review]
LGTM
