### PR TITLE
fix: Detect ECS Fargate launch type from capacity providers

### LINKED ISSUE #1349: `aws_ecs_service.capacity_provider_strategy` is not parsed as FARGATE deployment type
I am deploying a service and the prices that infracost is giving out seem wrong.
The main issue is it seems to think that the `aws_ecs_service` is free. Am I doing something wrong here or expecting something that cannot be done?
The resource is listed as a paid service here - https://www.infracost.io/docs/supported_resources/aws/

---

*additional context added after investigation*

Infracost uses `aws_ecs_service.launch_type` to determine what type of deployment the ecs service is (EC2/FARGATE). EC2 deployments are prices through `auto_scaling_group` and `aws_ecs_service` is marked as free.

When `aws_ecs_service.launch_type` is not specified it defaults to EC2 even if `capacity_provider_strategy` is set to a FARGATE type strategy.

We should change the `aws_ecs_service` to check `capacity_provider_strategy` block before determining the deployment type

### PR DESCRIPTION
**Pull request by tim775**
Fixes #1349

### CODE REVIEW

File: internal/providers/terraform/aws/ecs_service.go [hunk 1]
```diff
@@ -47,6 +48,88 @@ func NewECSService(d *schema.ResourceData, u *schema.UsageData) *schema.Resource
...
+	if launchType != "" {
+		return launchType
+	}
+
+	clusterRefs := d.References("cluster")
+	if len(clusterRefs) > 0 {
+		cluster := clusterRefs[0]
+
+		// check the cluster for a default capacity provider
+
```
Comment (hugorut) [inline internal/providers/terraform/aws/ecs_service.go:74]:
```suggestion
		// check the cluster for a default capacity provider
```

Comment (hugorut) [inline internal/providers/terraform/aws/ecs_service.go:74]:
```suggestion
		// check the cluster for a default capacity provider
```

File: internal/providers/terraform/aws/ecs_service.go [hunk 2]
```diff
@@ -47,6 +48,88 @@ func NewECSService(d *schema.ResourceData, u *schema.UsageData) *schema.Resource
...
+		for _, capProvider := range cluster.References("aws_ecs_cluster_capacity_providers.cluster_name") {
+			defaultStrategies := capProvider.Get("default_capacity_provider_strategy").Array()
+			if len(defaultStrategies) > 0 {
+				lt := getCapacityProviderLaunchType(defaultStrategies)
+				if lt == "FARGATE" {
+					return lt
+				}
+				if lt != "" {
+					launchType = lt
+				}
```
Comment (hugorut) [inline internal/providers/terraform/aws/ecs_service.go:99]:
```suggestion
				if lt != "" {
					return lt
				}
```

**Review by hugorut — APPROVED** [review]
🚀

File: internal/providers/terraform/aws/ecs_service.go (hunk 2 above)
Comment (tim775) [reply internal/providers/terraform/aws/ecs_service.go:99]: I think this suggestion isn't right because there can be multiple `aws_ecs_cluster_capacity_providers` and we want to keep looking to see if at least one supports fargate.

Comment (hugorut) [reply internal/providers/terraform/aws/ecs_service.go:99]: makes sense

File: internal/providers/terraform/aws/ecs_service.go (hunk 1 above)
Comment (hugorut) [reply internal/providers/terraform/aws/ecs_service.go:74]: just new line removal - but no biggie
