### PR TITLE
fix(aws): data transfer costs

### LINKED ISSUE #713: Investigate/fix AWS data transfer price warnings
```
INFRACOST_LOG_LEVEL=warn go test ./internal/providers/terraform/aws/data_transfer_test.go -v

=== RUN   TestDataTransferGoldenFile
=== PAUSE TestDataTransferGoldenFile
=== CONT  TestDataTransferGoldenFile
    tftest.go:274: Couldn't copy terraform init cache from /Users/ali/src/infracost/infracost/.test_cache/terraform_init
time="2021-05-24T16:25:59+01:00" level=warning msg="No products found for aws_data_transfer.ap-northeast-3 Intra-region data transfer, using 0.00"
time="2021-05-24T16:25:59+01:00" level=warning msg="No products found for aws_data_transfer.ap-northeast-3 Outbound data transfer to Internet, using 0.00"
time="2021-05-24T16:25:59+01:00" level=warning msg="No products found for aws_data_transfer.ap-northeast-3 Outbound data transfer to other regions, using 0.00"
time="2021-05-24T16:25:59+01:00" level=warning msg="No products found for aws_data_transfer.us-isob-east-1 Intra-region data transfer, using 0.00"
time="2021-05-24T16:25:59+01:00" level=warning msg="No products found for aws_data_transfer.us-isob-east-1 Outbound data transfer to Internet, using 0.00"
time="2021-05-24T16:25:59+01:00" level=warning msg="No products found for aws_data_transfer.us-isob-east-1 Outbound data transfer to other regions, using 0.00"
time="2021-05-24T16:25:59+01:00" level=warning msg="No products found for aws_data_transfer.us-west-1 Outbound data transfer to other regions, using 0.00"
time="2021-05-24T16:26:00+01:00" level=warning msg="No prices found for aws_data_transfer.cn-north-1 Outbound data transfer to Internet, using 0.00"
time="2021-05-24T16:26:00+01:00" level=warning msg="No products found for aws_data_transfer.cn-north-1 Outbound data transfer to other regions, using 0.00"
time="2021-05-24T16:26:00+01:00" level=warning msg="No products found for aws_data_transfer.us-iso-east-1 Intra-region data transfer, using 0.00"
time="2021-05-24T16:26:00+01:00" level=warning msg="No products found for aws_data_transfer.us-iso-east-1 Outbound data transfer to Internet, using 0.00"
time="2021-05-24T16:26:00+01:00" level=warning msg="No products found for aws_data_transfer.us-iso-east-1 Outbound data transfer to other regions, using 0.00"
time="2021-05-24T16:26:00+01:00" level=warning msg="No prices found for aws_data_transfer.cn-northwest-1 Outbound data transfer to Internet, using 0.00"
time="2021-05-24T16:26:00+01:00" level=warning msg="No products found for aws_data_transfer.cn-northwest-1 Outbound data transfer to other regions, using 0.00"
time="2021-05-24T16:26:00+01:00" level=warning msg="No products found for aws_data_transfer.us-west-1 Outbound data transfer to other regions, using 0.00"
time="2021-05-24T16:26:00+01:00" level=warning msg="No products found for aws_data_transfer.ap-northeast-3 Intra-region data transfer, using 0.00"
time="2021-05-24T16:26:00+01:00" level=warning msg="No products found for aws_data_transfer.ap-northeast-3 Outbound data transfer to Internet, using 0.00"
time="2021-05-24T16:26:00+01:00" level=warning msg="No products found for aws_data_transfer.ap-northeast-3 Outbound data transfer to other regions, using 0.00"
time="2021-05-24T16:26:00+01:00" level=warning msg="No products found for aws_data_transfer.us-isob-east-1 Intra-region data transfer, using 0.00"
time="2021-05-24T16:26:00+01:00" level=warning msg="No products found for aws_data_transfer.us-isob-east-1 Outbound data transfer to Internet, using 0.00"
time="2021-05-24T16:26:00+01:00" level=warning msg="No products found for aws_data_transfer.us-isob-east-1 Outbound data transfer to other regions, using 0.00"
time="2021-05-24T16:26:00+01:00" level=warning msg="No products found for aws_data_transfer.us-iso-east-1 Intra-region data transfer, using 0.00"
time="2021-05-24T16:26:00+01:00" level=warning msg="No products found for aws_data_transfer.us-iso-east-1 Outbound data transfer to Internet, using 0.00"
time="2021-05-24T16:26:00+01:00" level=warning msg="No products found for aws_data_transfer.us-iso-east-1 Outbound data transfer to other regions, using 0.00"
time="2021-05-24T16:26:00+01:00" level=warning msg="No prices found for aws_data_transfer.cn-northwest-1 Outbound data transfer to Internet, using 0.00"
time="2021-05-24T16:26:00+01:00" level=warning msg="No products found for aws_data_transfer.cn-northwest-1 Outbound data transfer to other regions, using 0.00"
time="2021-05-24T16:26:00+01:00" level=warning msg="No prices found for aws_data_transfer.cn-north-1 Outbound data transfer to Internet, using 0.00"
time="2021-05-24T16:26:00+01:00" level=warning msg="No products found for aws_data_transfer.cn-north-1 Outbound data transfer to other regions, using 0.00"
--- PASS: TestDataTransferGoldenFile (21.32s)
```

### PR DESCRIPTION
**Pull request by sinabakh**
Fix #713 

The changes can be divided into few sections:

## A) Unknown regions
Two regions `us-iso-east-1` and `us-isob-east-1` are totally missing in pricing API and amazon pages and I couldn't find much information for them. So I removed them.

## B) Wrong region names
One region's name was wrong which I assume might have changed recently. The `ap-northeast-3`'s name was changed from `Asia Pacific (Osaka-Local)` to `Asia Pacific (Osaka)`

## C) Data transfer to other regions mismatch
As I understood, since data transfer to all regions seems to have the same price the default `us-west-1` is selected. It caused two problems:

1. When the region is `us-west-1` itself, we should query data output to some other region. I used `us-west-2`.
2. Chinese regions `cn-north-1` and `cn-northwest-1` have data transfer prices just between themselves.

## C) Data transfer to the Internet
The pricing is actually a stepped price (like first 10TB, then next 40Tb, and ...). Most regions have the same steps but the 2 Chinese regions are different.
You can see all possible outputs by checking:
1. `us-east-2` for a full stepped costs
2. `us-east-1` for a partial stepping
3. `cn-north-1` and `cn-northwest-1` for no stepping at all

### CODE REVIEW

**Comment by sinabakh** [comment]
Since there were some changes and this resource is heavily used by our users, it would be great if another reviewer could double-check everything.

File: internal/providers/terraform/aws/data_transfer.go [hunk 1]
```diff
@@ -14,8 +16,6 @@ var regionMapping = map[string]string{
 	"us-west-1":       "US West (N. California)",
 	"us-west-2":       "US West (Oregon)",
 	"us-west-2-lax-1": "US West (Los Angeles)",
-	"us-iso-east-1":   "US ISO East",
-	"us-isob-east-1":  "US ISOB East (Ohio)",
```
Comment (alikhajeh1) [inline internal/providers/terraform/aws/data_transfer.go:18]: These are are secret regions, only used by US secret services :D so ok for them to be removed.

**Review by alikhajeh1 — COMMENTED** [review]
Thanks for taking a deep dive on this. One quick question before I review it in details: could the `CalculateTierBuckets` function we have not be used for the tier calcs? We use that in other places for this sort of thing but maybe this is different?

**Comment by sinabakh** [comment]
@alikhajeh1 I haven't seen `CalculateTierBuckets`, will investigate it.

**Comment by sinabakh** [comment]
@alikhajeh1 I did a refactor to use the mentioned function. It's really helpful.

File: internal/providers/terraform/aws/testdata/data_transfer_test/data_transfer_test.golden [hunk 2]
```diff
@@ -1,146 +1,207 @@
...
+ ├─ Outbound data transfer to Internet (over 150TB)        3,400  GB         $387.60 
+ └─ Outbound data transfer to other regions                  750  GB         $103.50 
+                                                                                     
+ aws_data_transfer.us-east-1                                                         
+ ├─ Intra-region data transfer                             1,000  GB          $10.00 
+ ├─ Outbound data transfer to Internet (first 10TB)       10,240  GB         $921.60 
+ ├─ Outbound data transfer to Internet (next 40TB)        40,960  GB       $3,481.60 
+ ├─ Outbound data transfer to Internet (next 100TB)        5,800  GB         $406.00 
+ ├─ Outbound data transfer to US East regions                500  GB           $5.00 
+ └─ Outbound data transfer to other regions                  750  GB          $15.00
```
Comment (alikhajeh1) [inline internal/providers/terraform/aws/testdata/data_transfer_test/data_transfer_test.golden:156]: I compared these numbers to https://calculator.aws/#/createCalculator/DataTransfer and the `Intra-region data transfer` one does not match, AWS says this:
```
Intra region:
(1000 GB x 0.01 USD per GB outbound) + (1000 GB x 0.01 USD per GB inbound) = 20.00 USD 
```

The AWS EC2 pricing page mentions:
```
 Data Transfer within the same AWS Region

Data transferred "in" to and "out" from Amazon EC2, Amazon RDS, Amazon Redshift, Amazon DynamoDB Accelerator (DAX), and Amazon ElastiCache instances, Elastic Network Interfaces or VPC Peering connections across Availability Zones in the same AWS Region is charged at $0.01/GB in each direction.

IPv4: Data transferred “in” to and “out” from public or Elastic IPv4 address is charged at $0.01/GB in each direction.
IPv6: Data transferred “in” to and “out” from an IPv6 address in a different VPC is charged at $0.01/GB in each direction.
```

So I guess we have to double the number in our calcs?

Comment (sinabakh) [reply internal/providers/terraform/aws/testdata/data_transfer_test/data_transfer_test.golden]: @alikhajeh1 Multiplied the quantity by 2 and updated the usage example. Anything else to change?

Comment (alikhajeh1) [reply internal/providers/terraform/aws/testdata/data_transfer_test/data_transfer_test.golden]: Love it - thank you!

**Comment by alikhajeh1** [comment]
This PR's description was great:

D1oABmS
